variables:
  GIT_CLEAN_FLAGS: none # disable git clean ** this is important **

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm --version
    - npm install
    - cd react-web-app/view/
    - ls
    - npm install --force
    - npm run build
    - cd ..
    - cd ..
    - npm start server.js
    - echo "deployed successfully :)"
